import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Finance tracker app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
            <div class="container">
            <h3>
              <a href='dashboard'>Dashboard</a>
            </h3>
            <h3>
              <a href='income'>income</a>
            </h3>
            <h3>
              <a href='spending'>spending</a>
            </h3>
        </div>
    </main>
    </>
  )
}
